### ISSUE TITLE
Small hight gets problems with Overflow

### ISSUE THREAD

**Issue by md-weber** [md-weber/flutter_explained_website#13]
![image](https://user-images.githubusercontent.com/8026644/90002861-8c472f00-dc93-11ea-834f-4d6991f721b2.png)

**Comment by yahu1031** [comment]
Ola @md-weber ,
Speaking logically we don't need to worry about it at all. Because the website is good at every screen we have in browser dev tool's device frames. Hope you can close this 😉. If still you are worried about it, then I can provide you my [code](https://github.com/yahu1031/flutter_explained_website), and that may fix this.

**Comment by md-weber** [comment]
The following PR will solve the issue: https://github.com/md-weber/flutter_explained_website/pull/14
